paths:
  oatuth_credentials: "~/.credentials/sheets_oauth.json"

sheet:
  name: "TurnSequence"
  place_worksheet: "Places"
  point_worksheet: "Points"
  directions_worksheet: "Directions"

map:
  places: [
    "New York City, New York, USA",
    "Boston, Massachusetts, USA",
    "Philadelphia, Pennsylvania, USA",
    "San Francisco, California, USA",
    "Los Angeles, California, USA",
    "Chicago, Illinois, USA",
    "Miami, Florida, USA",
    "London, UK",
    "Paris, France",
    "Amsterdam, Netherlands",
    "Berlin, Germany",
    "Rome, Italy",
    "Rio de Janeiro, Brazil",
    "Mumbai, India",
    "Singapore",
    "Melbourne, Australia",
    "Toronto, Canada"
    ]
  granulariy: ~

place_columns:
  id: "osm_id"
  name: "name"
  display_name: "display_name"
  lat_min: "lat_min"
  lon_min: "lon_min"
  lat_max: "lat_max"
  lon_max: "lon_max"
point_columns:
  id: "id"
  place_id: "osm_id"
  grid_lat: "grid_lat"
  grid_lon: "grid_lon"
  snapped_lat: "snapped_lat"
  snapped_lon: "snapped_lon"
direction_columns:
  id: "id"
  place_id: "osm_id"
  origin_id: "origin_id"
  destination_id: "destination_id"
  distance_km: "distance_km"
  raw_directions: "raw_directions"
  lr_directions: left_right_directions"
  direction_pairs: "direction_pairs"
